name: git tag release and npm package publisher
on:
  push:
    branches:
      - main
jobs:
  publish_tag_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Find and Replace Nuget
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "<configuration></configuration>"
          replace: ${{ secrets.NUGET_CONFIG }}
          regex: false

      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main

      - name: Pack
        run: dotnet pack --configuration debug

      - name: ls
        run: ls -la ./bin/debug/

      - name: Push
        run: dotnet nuget push "./bin/debug/*.nupkg"  --api-key ${{ secrets.GITHUB_TOKEN }}  --source "github"

    #   - run: |
    #       git config --global user.email "kevingil1910@gmail.com"
    #       git config --global user.name "${{ github.actor }}"
    #       echo "${{ steps.bump_version.outputs.tag }}"
    #   - run: npm version "${{ steps.bump_version.outputs.tag }}" && npm publish
    #     env:
    #       NODE_AUTH_TOKEN:
