name: git tag release and npm package publisher
on:
  push:
    branches:
      - main
jobs:
  publish_tag_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      - name: Install Versionize
        run: dotnet tool install --global Versionize

      - name: Versioning
        id: versionize
        run: versionize --changelog-all --exit-insignificant-commits
        continue-on-error: true

      - name: No release required
        if: steps.versionize.outcome != 'success'
        run: echo "Skipping Release. No release required."

      - name: Push changes to GitHub
        if: steps.versionize.outcome == 'success'
        run: |
          git push --follow-tags origin ${{ github.ref }}

      - name: Find and Replace Nuget
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "<configuration></configuration>"
          replace: ${{ secrets.NUGET_CONFIG }}
          regex: false

      - name: Pack
        run: dotnet pack --configuration debug

      - name: Push
        run: dotnet nuget push "./bin/Debug/*.nupkg"  --api-key ${{ secrets.TOKEN_GITHUB }}  --source "github"
